image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip/
    - venv/

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install coverage codecov pytest pytest-cov
  - pip install git+https://github.com/Theano/Theano.git#egg=Theano

test:
  script:
    - pytest --cov=transptrb
  artifacts:
    paths:
    - test/.cache/
