language: python

python:
  - "3.6"
  
before_install:
  - sudo apt-get install libblas-dev g++

# command to install dependencies
install:
  - pip install coverage
  - pip install git+https://github.com/Theano/Theano.git#egg=Theano

# command to run tests
script:
  - python tests/test_cycle.py
  - coverage run tests.py
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
