language: python

python:
  - "3.6"

before_install:
  - sudo apt-get install libblas-dev g++

# command to install dependencies
install:
  - pip install coverage codecov pytest pytest-cov
  - pip install git+https://github.com/Theano/Theano.git#egg=Theano

# command to run tests
script:
  - pytest --cov=./

after_success:
  - codecov
